# fly.toml app configuration file generated for shy-frost-8694 on 2023-07-04T21:22:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-frost-8694"
primary_region = "atl"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
